### ISSUE TITLE
Errors thrown on non-string inputs

### ISSUE THREAD

**Issue by gfcittolin** [rsenden/node-red-contrib-property-mapping#1]
Hi,

If you try sending a non-string input into your `map` node (but also happens with the `switch` one), and the "Ignore case" checkbox is set, the node throws the following errors:
![image](https://user-images.githubusercontent.com/2856088/58959453-898da780-877b-11e9-8b7d-52a43ad6ad40.png)
Maybe you can try null-checking and type casting before the `toLowerCase()` call :upside_down_face: 

Thanks for the great node. I find the `map` one can be particularly useful (although it can be extended for more useful things).

**Comment by rsenden** [comment]
Thanks for reporting this. I have just released version 1.0.2 that should fix this issue. The new version is already available at https://www.npmjs.com/package/node-red-contrib-map, and should be listed at https://flows.nodered.org/node/node-red-contrib-map any time soon.
